<a href="https://colab.research.google.com/github/Anish-185/California-housing-using-SVR/blob/main/CaliforniaH_SVR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVR
from sklearn.metrics import mean_squared_error

In [2]:
cali=fetch_california_housing()
X=cali['data']
y=cali['target']

In [3]:
X

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [4]:
X

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [5]:
X[:5]

array([[ 8.32520000e+00,  4.10000000e+01,  6.98412698e+00,
         1.02380952e+00,  3.22000000e+02,  2.55555556e+00,
         3.78800000e+01, -1.22230000e+02],
       [ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00,
         9.71880492e-01,  2.40100000e+03,  2.10984183e+00,
         3.78600000e+01, -1.22220000e+02],
       [ 7.25740000e+00,  5.20000000e+01,  8.28813559e+00,
         1.07344633e+00,  4.96000000e+02,  2.80225989e+00,
         3.78500000e+01, -1.22240000e+02],
       [ 5.64310000e+00,  5.20000000e+01,  5.81735160e+00,
         1.07305936e+00,  5.58000000e+02,  2.54794521e+00,
         3.78500000e+01, -1.22250000e+02],
       [ 3.84620000e+00,  5.20000000e+01,  6.28185328e+00,
         1.08108108e+00,  5.65000000e+02,  2.18146718e+00,
         3.78500000e+01, -1.22250000e+02]])

In [6]:
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [7]:
y[:5]

array([4.526, 3.585, 3.521, 3.413, 3.422])

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [9]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [10]:
lin_svr=LinearSVR(epsilon=1.7,random_state=42)
lin_svr.fit(X_train_scaled,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVR(epsilon=1.7, random_state=42)

In [11]:
lin_svr

LinearSVR(epsilon=1.7, random_state=42)

In [12]:
y_pred=lin_svr.predict(X_train_scaled)

mse=mean_squared_error(y_train,y_pred)
mse

0.9490302734470016

In [13]:
np.sqrt(mse)

np.float64(0.9741818482434383)

In [14]:
from sklearn.svm import SVR

In [15]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import reciprocal,uniform

In [16]:
param_distributions={'gamma': reciprocal(0.001,0.1),'C' :uniform(1,10)}
rnd_search_cv=RandomizedSearchCV(SVR(),param_distributions,n_iter=10,verbose=2,cv=3,random_state=42)
rnd_search_cv.fit(X_train_scaled,y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits
[CV] END .....C=4.745401188473625, gamma=0.07969454818643935; total time=  15.7s
[CV] END .....C=4.745401188473625, gamma=0.07969454818643935; total time=   7.9s
[CV] END .....C=4.745401188473625, gamma=0.07969454818643935; total time=   6.9s
[CV] END .....C=8.31993941811405, gamma=0.015751320499779727; total time=   7.5s
[CV] END .....C=8.31993941811405, gamma=0.015751320499779727; total time=   6.2s
[CV] END .....C=8.31993941811405, gamma=0.015751320499779727; total time=   7.5s
[CV] END ....C=2.560186404424365, gamma=0.002051110418843397; total time=   5.9s
[CV] END ....C=2.560186404424365, gamma=0.002051110418843397; total time=   7.1s
[CV] END ....C=2.560186404424365, gamma=0.002051110418843397; total time=   5.8s
[CV] END ....C=1.5808361216819946, gamma=0.05399484409787434; total time=   6.9s
[CV] END ....C=1.5808361216819946, gamma=0.05399484409787434; total time=   5.8s
[CV] END ....C=1.5808361216819946, gamma=0.05399

RandomizedSearchCV(cv=3, estimator=SVR(),
                   param_distributions={'C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x787fd78ef4d0>,
                                        'gamma': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x787fd78ef3e0>},
                   random_state=42, verbose=2)

In [17]:
rnd_search_cv.best_estimator_

SVR(C=np.float64(4.745401188473625), gamma=np.float64(0.07969454818643935))

In [18]:
y_predi=rnd_search_cv.best_estimator_.predict(X_train_scaled)
mse=mean_squared_error(y_predi,y_train)
mse

0.3350482644727063

In [19]:
np.sqrt(mse)

np.float64(0.5788335377919167)